#line 1 "lex.yy.cpp"

#line 3 "lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[316] =
    {   0,
        0,    0,  100,   98,   97,   97,   85,   98,   91,   84,
       98,   79,   80,   89,   88,   76,   87,   83,   90,   41,
       42,   77,   73,   92,   78,   93,   96,   39,   39,   81,
       82,   94,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   74,
       95,   75,   86,   72,    0,   50,    0,   58,   75,   67,
       59,    0,    0,   56,   64,   54,   65,   55,   66,    0,
       45,    1,   57,   46,   41,    0,    0,   41,   41,    0,
       41,   42,   42,   42,   42,   82,   74,   81,   63,   69,
       71,   70,   62,   39,    0,    0,   60,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   11,   39,   39,   39,
       39,   39,   39,   19,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   61,   68,   43,   51,    0,
       45,   45,    0,   46,    0,   44,   41,   41,   41,   41,
        0,   40,   42,   42,   42,   42,   53,   52,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   17,   39,   39,   22,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,    0,   45,    0,   45,    0,   46,   44,   41,
       48,   49,   40,    0,   40,   40,   42,   39,   39,   39,

        2,   39,    5,    6,   39,   39,   39,   39,   13,   14,
       39,   39,   18,   39,   23,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   36,   39,   39,
        0,   45,   48,    0,   48,   49,    0,   40,   40,    0,
       47,   40,   40,    3,   39,   39,    4,    8,   39,   39,
       39,   39,   16,   39,   39,   39,   39,   27,   39,   39,
       39,   39,   39,   39,   34,   39,   39,   38,    0,   48,
       48,    0,    0,   49,   47,   40,   39,   39,   39,   39,
       12,   15,   21,   39,   39,   26,   28,   29,   30,   31,
       32,   39,   39,   39,    0,   48,   39,   39,   39,   10,

       39,   39,   33,   39,   39,    7,   39,    9,   24,   25,
       35,   37,   39,   20,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   29,   30,
       31,   31,   32,   31,   31,   33,   31,   31,   31,   34,
       31,   31,   31,   31,   35,   31,   31,   36,   31,   31,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   31,   51,   52,   53,   54,
       55,   56,   31,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        6,    6,    7,    7,    6,    6,    1,    1,    1,    1,
        6,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    7,    6,    6,    6,    7,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[322] =
    {   0,
        0,    0,  540,  541,  541,  541,  516,   65,   48,   66,
      500,  541,  541,  514,   62,  541,   63,   61,   70,   89,
       80,  512,  541,   94,  512,   59,  541,    0,   83,  541,
      541,  511,  101,  473,  475,   81,   29,   38,   50,  476,
       65,  475,    0,  483,   88,  464,  473,  471,  476,  541,
       87,  541,  541,  541,   89,  541,    0,  541,  541,  541,
      541,  113,  516,  541,  541,  541,  541,  541,  541,  508,
      126,  541,  541,  146,  151,  170,  188,  148,   87,  507,
      122,  195,  161,  101,  166,  541,  541,  541,  498,  541,
      541,  541,  497,    0,  153,  481,  541,  463,  462,  463,

      456,  468,  455,  470,  457,  463,  449,  450,  447,  447,
      450,  447,  444,    0,  108,  448,  161,  446,   83,   54,
      450,  443,  165,  175,  448,  541,  541,  541,  541,  217,
      541,  220,  240,  541,  225,  243,  111,  541,  464,  444,
        0,  236,  205,  541,  462,  442,  541,  541,  438,  439,
      449,  435,  447,  442,  430,  103,  444,  442,  438,  430,
      436,  439,    0,  425,  429,    0,  430,  427,  417,  415,
      417,  419,  426,  411,  399,  399,  405,  393,  397,  401,
      403,  391,  260,  264,  286,  541,  267,  289,  541,  541,
      212,  268,  254,  309,  223,  239,  541,  390,  385,  392,

        0,  388,    0,    0,  379,  387,  376,  383,    0,    0,
      377,  374,    0,  378,    0,  371,  371,  368,  365,  377,
      367,  371,  376,  375,  373,  363,  365,    0,  351,  362,
      312,  315,  541,  325,  313,  541,  337,  258,  541,  340,
      353,  374,  352,    0,  347,  341,    0,    0,  333,  333,
      338,  328,    0,  322,  307,  314,  309,    0,  316,  313,
      309,  293,  301,  294,    0,  284,  285,    0,  356,  359,
      541,  376,  362,  379,  541,  541,  279,  263,  255,  254,
        0,    0,    0,  266,  266,    0,    0,    0,    0,    0,
        0,  262,  234,  211,  384,  397,  185,  191,  186,    0,

      165,  158,    0,  159,  149,    0,  133,    0,    0,    0,
        0,    0,  113,    0,  541,  449,  456,  459,  463,  137,
      464
    } ;

static const flex_int16_t yy_def[322] =
    {   0,
      315,    1,  315,  315,  315,  315,  315,  316,  315,  315,
      317,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  318,  318,  315,
      315,  315,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  315,
      315,  315,  315,  315,  316,  315,  316,  315,  315,  315,
      315,  317,  317,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  319,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  318,  316,  317,  315,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      320,  319,  315,  315,  315,  315,  315,  315,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  315,  315,  315,  315,  315,  315,  315,  315,
      320,  321,  315,  315,  315,  315,  315,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      315,  315,  315,  315,  321,  315,  315,  315,  315,  315,
      315,  315,  315,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  315,  315,
      315,  315,  315,  315,  315,  315,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  315,  315,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,    0,  315,  315,  315,  315,  315,
      315
    } ;

static const flex_int16_t yy_nxt[611] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   28,
       28,   28,   29,   28,   28,   28,   30,    4,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   28,   41,
       28,   42,   28,   28,   28,   43,   44,   45,   46,   47,
       48,   49,   28,   28,   28,   50,   51,   52,   53,   56,
       58,   59,   60,   65,  106,   70,   67,   71,   71,   71,
       72,   92,   93,  107,   66,   68,   69,   95,   61,  108,
       96,  109,   73,   56,   74,  174,   82,   82,   82,   87,

      110,  111,   57,   74,  112,   75,   75,   76,   77,  126,
      175,  114,   83,   88,   84,   89,   90,   77,  115,  139,
      128,   78,  103,   79,   80,   77,   57,   98,   99,  104,
      172,   85,  100,  145,   77,  105,  118,  119,  140,   84,
       81,  191,   71,   71,   71,  138,  120,  173,   79,  121,
       63,   80,  146,  127,  130,  131,  138,   56,  131,  165,
      205,  206,  132,  132,  132,   74,  166,   75,   75,   76,
      138,  130,  131,  137,  133,  134,  314,  131,  134,   77,
      137,  138,  138,   78,   74,   79,   76,   76,   76,  313,
       57,  133,  134,  143,  312,  144,   77,  134,   77,  135,

      144,  135,   81,  311,  136,  136,  136,  138,  168,   74,
       79,   82,   82,   82,  178,   77,  310,  143,  169,  170,
      144,  309,  179,   77,  180,  144,  181,   83,  183,   84,
      183,  308,  307,  184,  184,  184,  132,  132,  132,  144,
       77,  136,  136,  136,  233,  234,   85,  306,  185,  186,
      192,  187,  186,  187,   84,  242,  188,  188,  188,  136,
      136,  136,  305,  233,  144,  185,  186,  234,  193,  194,
      195,  186,  189,  239,  243,  189,  184,  184,  184,  304,
      184,  184,  184,  188,  188,  188,  238,  196,  239,  189,
      238,  194,  239,  131,  189,  195,  131,  231,  239,  231,

      236,  237,  232,  232,  232,  188,  188,  188,  303,  302,
      131,  301,  300,  239,  299,  131,  298,  239,  134,  236,
      240,  134,  240,  237,  297,  241,  241,  241,  232,  232,
      232,  232,  232,  232,  294,  134,  269,  293,  269,  292,
      134,  270,  270,  270,  186,  271,  272,  186,  273,  291,
      273,  290,  289,  274,  274,  274,  241,  241,  241,  288,
      287,  186,  286,  285,  271,  284,  186,  283,  272,  241,
      241,  241,  270,  270,  270,  270,  270,  270,  274,  274,
      274,  282,  275,  281,  280,  275,  279,  295,  233,  295,
      278,  233,  296,  296,  296,  274,  274,  274,  277,  275,

      296,  296,  296,  276,  275,  233,  276,  268,  236,  267,
      233,  236,  266,  296,  296,  296,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  236,  271,  256,  255,  271,
      236,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  230,  271,  229,  228,  227,  226,  271,   55,
      225,   55,   55,   55,   55,   55,   62,  224,  223,   62,
       62,   62,   62,   94,   94,   94,  142,  142,  235,  222,
      235,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  204,  203,  202,  201,
      200,  199,  198,  197,  197,  190,  190,  182,  177,  176,

      171,  167,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,   63,  148,
      147,  141,  129,   62,  125,  124,  123,  122,  117,  116,
      113,  102,  101,   97,   91,   86,   64,   63,   54,  315,
        3,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315
    } ;

static const flex_int16_t yy_chk[611] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
        9,    9,   10,   15,   37,   18,   17,   18,   18,   18,
       19,   26,   26,   37,   15,   17,   17,   29,   10,   38,
       29,   38,   19,   55,   21,  120,   21,   21,   21,   24,

       38,   39,    8,   20,   39,   20,   20,   20,   21,   51,
      120,   41,   21,   24,   21,   24,   24,   20,   41,   79,
       62,   20,   36,   20,   20,   21,   55,   33,   33,   36,
      119,   21,   33,   84,   20,   36,   45,   45,   79,   21,
       20,  320,   71,   71,   71,  137,   45,  119,   20,   45,
       62,   20,   84,   51,   71,   71,   81,   95,   71,  115,
      156,  156,   74,   74,   74,   75,  115,   75,   75,   75,
      137,   71,   71,   81,   74,   74,  313,   71,   74,   75,
       78,   81,   78,   75,   76,   75,   76,   76,   76,  307,
       95,   74,   74,   83,  305,   83,   75,   74,   76,   77,

       85,   77,   75,  304,   77,   77,   77,   78,  117,   82,
       75,   82,   82,   82,  123,   76,  302,   85,  117,  117,
       83,  301,  123,   82,  124,   85,  124,   82,  130,   82,
      130,  299,  298,  130,  130,  130,  132,  132,  132,  143,
       82,  135,  135,  135,  191,  191,   82,  297,  132,  132,
      142,  133,  132,  133,   82,  195,  133,  133,  133,  136,
      136,  136,  294,  191,  143,  132,  132,  191,  142,  142,
      142,  132,  136,  196,  195,  136,  183,  183,  183,  293,
      184,  184,  184,  187,  187,  187,  193,  142,  193,  136,
      196,  142,  238,  184,  136,  142,  184,  185,  196,  185,

      192,  192,  185,  185,  185,  188,  188,  188,  292,  285,
      184,  284,  280,  193,  279,  184,  278,  238,  188,  192,
      194,  188,  194,  192,  277,  194,  194,  194,  231,  231,
      231,  232,  232,  232,  267,  188,  234,  266,  234,  264,
      188,  234,  234,  234,  232,  235,  235,  232,  237,  263,
      237,  262,  261,  237,  237,  237,  240,  240,  240,  260,
      259,  232,  257,  256,  235,  255,  232,  254,  235,  241,
      241,  241,  269,  269,  269,  270,  270,  270,  273,  273,
      273,  252,  241,  251,  250,  241,  249,  272,  270,  272,
      246,  270,  272,  272,  272,  274,  274,  274,  245,  241,

      295,  295,  295,  243,  241,  270,  242,  230,  274,  229,
      270,  274,  227,  296,  296,  296,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  274,  296,  217,  216,  296,
      274,  214,  212,  211,  208,  207,  206,  205,  202,  200,
      199,  198,  182,  296,  181,  180,  179,  178,  296,  316,
      177,  316,  316,  316,  316,  316,  317,  176,  175,  317,
      317,  317,  317,  318,  318,  318,  319,  319,  321,  174,
      321,  173,  172,  171,  170,  169,  168,  167,  165,  164,
      162,  161,  160,  159,  158,  157,  155,  154,  153,  152,
      151,  150,  149,  146,  145,  140,  139,  125,  122,  121,

      118,  116,  113,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   96,   93,
       89,   80,   70,   63,   49,   48,   47,   46,   44,   42,
       40,   35,   34,   32,   25,   22,   14,   11,    7,    3,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mini_c.l"
#line 13 "mini_c.l"
#include <stdio.h>
#include <string.h>
#include "ast.h"
#include "mini_c.tab.hpp"
#define SET_SVAL  yylval.sval = strdup(yytext)
void count(void);

void comment(void);

int column = 0;
int  check_type(void);
void error(const char*);   /* 已在 .l 末尾实现 */

extern int yylineno;

#define YY_USER_ACTION                           \
  yylloc.first_line   = yylineno;                \
  yylloc.first_column = column;                  \
  yylloc.last_line    = yylineno;                \
  yylloc.last_column  = column + yyleng - 1;     \
  column += yyleng;



#line 737 "lex.yy.cpp"
#line 738 "lex.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 40 "mini_c.l"

#line 957 "lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 541 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "mini_c.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 44 "mini_c.l"
{ count(); return(AUTO); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "mini_c.l"
{ count(); return(BOOL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "mini_c.l"
{ count(); return(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "mini_c.l"
{ count(); return(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "mini_c.l"
{ count(); return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "mini_c.l"
{ count(); return(COMPLEX); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "mini_c.l"
{ count(); return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "mini_c.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "mini_c.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "mini_c.l"
{ count(); return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "mini_c.l"
{ count(); return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "mini_c.l"
{ count(); return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "mini_c.l"
{ count(); return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "mini_c.l"
{ count(); return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "mini_c.l"
{ count(); return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "mini_c.l"
{ count(); return(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "mini_c.l"
{ count(); return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "mini_c.l"
{ count(); return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "mini_c.l"
{ count(); return(IMAGINARY); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "mini_c.l"
{ count(); return(INLINE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "mini_c.l"
{ count(); return(INT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "mini_c.l"
{ count(); return(LONG); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "mini_c.l"
{ count(); return(REGISTER); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "mini_c.l"
{ count(); return(RESTRICT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "mini_c.l"
{ count(); return(RETURN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "mini_c.l"
{ count(); return(SHORT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "mini_c.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "mini_c.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "mini_c.l"
{ count(); return(STATIC); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "mini_c.l"
{ count(); return(STRUCT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "mini_c.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "mini_c.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "mini_c.l"
{ count(); return(UNION); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "mini_c.l"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "mini_c.l"
{ count(); return(VOID); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "mini_c.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "mini_c.l"
{ count(); return(WHILE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "mini_c.l"
{ count(); SET_SVAL; return(check_type()); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 85 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 86 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 87 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 89 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 91 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 92 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 93 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 94 "mini_c.l"
{ count(); SET_SVAL; return(CONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "mini_c.l"
{ count(); SET_SVAL; return(STRING_LITERAL); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "mini_c.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "mini_c.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "mini_c.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 102 "mini_c.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 103 "mini_c.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 104 "mini_c.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 105 "mini_c.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 106 "mini_c.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "mini_c.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 108 "mini_c.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 109 "mini_c.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 110 "mini_c.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 111 "mini_c.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 112 "mini_c.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 113 "mini_c.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 114 "mini_c.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 115 "mini_c.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 116 "mini_c.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 117 "mini_c.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 118 "mini_c.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 119 "mini_c.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 120 "mini_c.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 121 "mini_c.l"
{ count(); return(';'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 122 "mini_c.l"
{ count(); return('{'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 123 "mini_c.l"
{ count(); return('}'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 124 "mini_c.l"
{ count(); return(','); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 125 "mini_c.l"
{ count(); return(':'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 126 "mini_c.l"
{ count(); return('='); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 127 "mini_c.l"
{ count(); return('('); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 128 "mini_c.l"
{ count(); return(')'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 129 "mini_c.l"
{ count(); return('['); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 130 "mini_c.l"
{ count(); return(']'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 131 "mini_c.l"
{ count(); return('.'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 132 "mini_c.l"
{ count(); return('&'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 133 "mini_c.l"
{ count(); return('!'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 134 "mini_c.l"
{ count(); return('~'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 135 "mini_c.l"
{ count(); return('-'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 136 "mini_c.l"
{ count(); return('+'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 137 "mini_c.l"
{ count(); return('*'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 138 "mini_c.l"
{ count(); return('/'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 139 "mini_c.l"
{ count(); return('%'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 140 "mini_c.l"
{ count(); return('<'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 141 "mini_c.l"
{ count(); return('>'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 142 "mini_c.l"
{ count(); return('^'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 143 "mini_c.l"
{ count(); return('|'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 144 "mini_c.l"
{ count(); return('?'); }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 146 "mini_c.l"
{ count(); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 147 "mini_c.l"
{ /* Add code to complain about unmatched characters */ }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 149 "mini_c.l"
ECHO;
	YY_BREAK
#line 1520 "lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 315);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "mini_c.l"


int yywrap(void)
{
	return 1;
}


void comment(void)
{
	char c, prev = 0;

	while ((c = yyinput()) != 0)      /* (EOF maps to 0) */
	{
		if (c == '/' && prev == '*')
			return;
		prev = c;
	}
	error("unterminated comment");
}


/* int column = 0; */

void count(void)
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
		{
			column = 0;
		}
		else if (yytext[i] == '\t')
			{
			column += 8 - (column % 8);
			}
		else
			{
			column++;
			}
	ECHO;
}


int check_type(void)
{
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return TYPE_NAME;
*
*	return IDENTIFIER;
*/

/*
*	it actually will only return IDENTIFIER
*/

	return IDENTIFIER;
}
